import { Container, Typography, Card, CardContent, Button, Box, Grid, TextField, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Stack, MenuItem, Chip, Select, FormControl, InputLabel, Drawer } from '@mui/material';
import { Edit, Delete, Add, ChevronRight, Save, Close, Download } from '@mui/icons-material';
import Layout from '@/components/Layout';
import Breadcrumb from '@/components/Breadcrumb';
import FormDrawer from '@/components/FormDrawer';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import api from '@/lib/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Helper function to export to CSV
const exportToCSV = (data: any[], filename: string) => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(','),
    ...data.map(row => headers.map(header => {
      const value = row[header];
      return typeof value === 'string' && value.includes(',') ? `"${value}"` : value;
    }).join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.csv`;
  link.click();
  window.URL.revokeObjectURL(url);
};

// Helper function to export to PDF with clean UI
const exportToPDF = async (data: any[], filename: string, title: string) => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  try {
    // Load and add logo
    const logoResponse = await fetch('/logo-white.png');
    const logoBlob = await logoResponse.blob();
    const logoUrl = URL.createObjectURL(logoBlob);
    const img = new Image();
    img.src = logoUrl;
    
    img.onload = () => {
      // Add logo at top center with margin
      const logoWidth = 30;
      const logoHeight = 30;
      const logoX = (pageWidth - logoWidth) / 2;
      doc.addImage(logoUrl, 'PNG', logoX, 10, logoWidth, logoHeight);
      
      // Add title below logo
      doc.setFontSize(14);
      doc.setFont('Inter', 'bold');
      doc.setTextColor(51, 51, 51);
      doc.text(title, pageWidth / 2, 50, { align: 'center' });
      
      // Add metadata
      doc.setFontSize(9);
      doc.setFont('Inter', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, pageWidth / 2, 58, { align: 'center' });
      
      // Add table
      const headers = Object.keys(data[0]);
      const rows = data.map(item => headers.map(header => item[header]));
      
      autoTable(doc, {
        head: [headers],
        body: rows,
        startY: 66,
        theme: 'grid',
        headStyles: {
          fillColor: [255, 255, 255],
          textColor: [51, 51, 51],
          fontStyle: 'bold',
          fontSize: 9,
          halign: 'center',
          lineColor: [200, 200, 200],
          lineWidth: 0.2,
          font: 'Inter',
        },
        bodyStyles: {
          fontSize: 8,
          textColor: [51, 51, 51],
          lineColor: [220, 220, 220],
          lineWidth: 0.2,
          font: 'Inter',
        },
        alternateRowStyles: {
          fillColor: [255, 255, 255],
        },
        margin: { top: 66, right: 10, bottom: 20, left: 10 },
      });
      
      // Add footer
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.2);
      doc.line(10, pageHeight - 18, pageWidth - 10, pageHeight - 18);
      
      doc.setFontSize(8);
      doc.setFont('Inter', 'normal');
      doc.setTextColor(120, 120, 120);
      doc.text('Generated by: Voltrix ERP', 10, pageHeight - 12);
      doc.text(`Document ID: ${filename}`, 10, pageHeight - 8);
      doc.text(`Status: Accepted`, pageWidth - 10, pageHeight - 12, { align: 'right' });
      doc.text(`Page 1`, pageWidth - 10, pageHeight - 8, { align: 'right' });
      
      doc.save(`${filename}.pdf`);
      URL.revokeObjectURL(logoUrl);
    };
  } catch (error) {
    console.error('Error loading logo:', error);
    // Fallback without logo
    doc.setFontSize(14);
    doc.setFont('Inter', 'bold');
    doc.setTextColor(51, 51, 51);
    doc.text(title, pageWidth / 2, 30, { align: 'center' });
    
    doc.setFontSize(9);
    doc.setFont('Inter', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, pageWidth / 2, 38, { align: 'center' });
    
    const headers = Object.keys(data[0]);
    const rows = data.map(item => headers.map(header => item[header]));
    
    autoTable(doc, {
      head: [headers],
      body: rows,
      startY: 46,
      theme: 'grid',
      headStyles: {
        fillColor: [255, 255, 255],
        textColor: [51, 51, 51],
        fontStyle: 'bold',
        fontSize: 9,
        halign: 'center',
        lineColor: [200, 200, 200],
        lineWidth: 0.2,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: [51, 51, 51],
        lineColor: [220, 220, 220],
        lineWidth: 0.2,
      },
      alternateRowStyles: {
        fillColor: [255, 255, 255],
      },
      margin: { top: 46, right: 10, bottom: 20, left: 10 },
    });
    
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.2);
    doc.line(10, pageHeight - 18, pageWidth - 10, pageHeight - 18);
    
    doc.setFontSize(8);
    doc.setFont('Inter', 'normal');
    doc.setTextColor(120, 120, 120);
    doc.text('Generated by: Voltrix ERP', 10, pageHeight - 12);
    doc.text(`Document ID: ${filename}`, 10, pageHeight - 8);
    doc.text(`Status: Accepted`, pageWidth - 10, pageHeight - 12, { align: 'right' });
    doc.text(`Page 1`, pageWidth - 10, pageHeight - 8, { align: 'right' });
    
    doc.save(`${filename}.pdf`);
  }
};

interface Attendance {
  id: number;
  emp_id: number;
  date: string;
  status: string;
  check_in: string;
  check_out: string;
}

interface Employee {
  id: number;
  emp_id: string;
  first_name: string;
  last_name: string;
  status: string;
}

interface EditingRow {
  emp_id: number;
  status: string;
  check_in: string;
  check_out: string;
}

interface EmployeeAttendanceHistory {
  emp_id: number;
  emp_name: string;
  attendances: Attendance[];
}

export default function Attendance() {
  const router = useRouter();
  const [attendances, setAttendances] = useState<Attendance[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [activeEmployees, setActiveEmployees] = useState<Employee[]>([]);
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [editingRows, setEditingRows] = useState<{ [key: number]: EditingRow }>({});
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [selectedEmployee, setSelectedEmployee] = useState<Employee | null>(null);
  const [employeeAttendanceHistory, setEmployeeAttendanceHistory] = useState<Attendance[]>([]);
  const [rangeStart, setRangeStart] = useState(new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().split('T')[0]);
  const [rangeEnd, setRangeEnd] = useState(new Date().toISOString().split('T')[0]);

  useEffect(() => {
    fetchAttendances();
    fetchEmployees();
  }, [selectedDate]);

  const fetchAttendances = async () => {
    try {
      const response = await api.get('/api/attendance');
      setAttendances(response.data);
    } catch (error) {
      console.error('Error fetching attendance:', error);
    }
  };

  const fetchEmployees = async () => {
    try {
      const response = await api.get('/api/employees');
      setEmployees(response.data);
      const active = response.data.filter((emp: Employee) => emp.status === 'Active');
      setActiveEmployees(active);
    } catch (error) {
      console.error('Error fetching employees:', error);
    }
  };

  const getAttendanceForEmployee = (empId: number) => {
    return attendances.find(a => a.emp_id === empId && a.date === selectedDate);
  };

  const openEmployeeDrawer = async (emp: Employee) => {
    setSelectedEmployee(emp);
    setDrawerOpen(true);
    // Fetch all attendance records for this employee
    try {
      const response = await api.get(`/api/attendance?emp_id=${emp.id}`);
      setEmployeeAttendanceHistory(response.data);
    } catch (error) {
      console.error('Error fetching employee attendance history:', error);
    }
  };

  const closeEmployeeDrawer = () => {
    setDrawerOpen(false);
    setSelectedEmployee(null);
    setEmployeeAttendanceHistory([]);
  };

  const getFilteredAttendance = () => {
    return employeeAttendanceHistory.filter(a => a.date >= rangeStart && a.date <= rangeEnd);
  };

  const downloadAttendanceData = async (format: 'csv' | 'pdf') => {
    const data = attendances
      .filter(a => a.date === selectedDate)
      .map(a => {
        const emp = employees.find(e => e.id === a.emp_id);
        return {
          'Employee ID': emp?.emp_id || '',
          'Employee Name': emp ? `${emp.first_name} ${emp.last_name}` : '',
          'Date': a.date,
          'Status': a.status,
          'Check In': a.check_in || '-',
          'Check Out': a.check_out || '-',
        };
      });

    if (format === 'csv') {
      exportToCSV(data, `attendance_${selectedDate}`);
    } else {
      await exportToPDF(data, `attendance_${selectedDate}`, `Attendance Report - ${selectedDate}`);
    }
  };

  const downloadEmployeeHistory = async (format: 'csv' | 'pdf') => {
    const data = getFilteredAttendance().map(a => ({
      'Date': a.date,
      'Status': a.status,
      'Check In': a.check_in || '-',
      'Check Out': a.check_out || '-',
    }));

    if (format === 'csv') {
      exportToCSV(data, `${selectedEmployee?.first_name}_${selectedEmployee?.last_name}_attendance_${rangeStart}_to_${rangeEnd}`);
    } else {
      await exportToPDF(data, `${selectedEmployee?.first_name}_${selectedEmployee?.last_name}_attendance_${rangeStart}_to_${rangeEnd}`, `Attendance History - ${selectedEmployee?.first_name} ${selectedEmployee?.last_name} (${rangeStart} to ${rangeEnd})`);
    }
  };

  const startEditingRow = (emp: Employee) => {
    const existing = getAttendanceForEmployee(emp.id);
    setEditingRows(prev => ({
      ...prev,
      [emp.id]: {
        emp_id: emp.id,
        status: existing?.status || 'Present',
        check_in: existing?.check_in || '',
        check_out: existing?.check_out || '',
      }
    }));
  };

  const cancelEditingRow = (empId: number) => {
    setEditingRows(prev => {
      const newState = { ...prev };
      delete newState[empId];
      return newState;
    });
  };

  const saveAttendanceRow = async (empId: number) => {
    try {
      const rowData = editingRows[empId];
      const existing = getAttendanceForEmployee(empId);

      if (existing) {
        await api.put(`/api/attendance/${existing.id}`, {
          emp_id: empId,
          date: selectedDate,
          status: rowData.status,
          check_in: rowData.check_in || null,
          check_out: rowData.check_out || null,
        });
      } else {
        await api.post('/api/attendance', {
          emp_id: empId,
          date: selectedDate,
          status: rowData.status,
          check_in: rowData.check_in || null,
          check_out: rowData.check_out || null,
        });
      }

      fetchAttendances();
      cancelEditingRow(empId);
    } catch (error) {
      console.error('Error saving attendance:', error);
      alert('Error saving attendance. Please check the console for details.');
    }
  };

  const handleRowInputChange = (empId: number, field: string, value: string) => {
    setEditingRows(prev => ({
      ...prev,
      [empId]: {
        ...prev[empId],
        [field]: value,
      }
    }));
  };

  return (
    <Layout title="Attendance" drawerOpen={drawerOpen}>
      <Container maxWidth="lg">
        <Breadcrumb
          items={[
            { label: 'Dashboard', href: '/' },
            { label: 'Human Resources' },
            { label: 'Attendance' },
          ]}
          prevHref="/hr-payroll"
          nextHref="/payroll"
        />

        <Box sx={{ mb: 3, display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: 1 }}>
          <TextField
            type="date"
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
            InputLabelProps={{ shrink: true }}
            size="small"
            variant="standard"
            sx={{ width: '140px' }}
          />
          
          <Box sx={{ width: '1px', height: '24px', backgroundColor: '#e8e8e8', mx: 0.5 }} />
          
          <Button size="small" variant="text" startIcon={<Download />} onClick={() => downloadAttendanceData('csv')} sx={{ fontSize: '0.7rem', textTransform: 'none', color: '#333333', py: 0.3, px: 0.8 }}>
            CSV
          </Button>
          <Button size="small" variant="text" startIcon={<Download />} onClick={() => downloadAttendanceData('pdf')} sx={{ fontSize: '0.7rem', textTransform: 'none', color: '#333333', py: 0.3, px: 0.8 }}>
            PDF
          </Button>
        </Box>

        <Card sx={{ border: 'none', boxShadow: 'none' }}>
          <CardContent sx={{ p: 0 }}>
            <TableContainer component={Paper} sx={{ border: 'none', boxShadow: 'none' }}>
              <Table>
                <TableHead>
                  <TableRow sx={{ backgroundColor: '#fafafa' }}>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Employee</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Status</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Check In</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Check Out</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {activeEmployees.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={5} sx={{ textAlign: 'center', py: 3, color: '#999999', fontSize: '0.8rem', borderBottom: '1px solid #f0f0f0' }}>
                        No active employees found
                      </TableCell>
                    </TableRow>
                  ) : (
                    activeEmployees.map((emp) => {
                      const attendance = getAttendanceForEmployee(emp.id);
                      const isEditing = editingRows[emp.id];

                      return (
                        <TableRow key={emp.id} sx={{ borderBottom: '1px solid #f0f0f0', '&:hover': { backgroundColor: '#fafafa' } }}>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>
                            <Box sx={{ cursor: 'pointer' }} onClick={() => openEmployeeDrawer(emp)}>
                              <Typography variant="body2" sx={{ fontWeight: 400, fontSize: '0.8rem', color: '#333333', '&:hover': { textDecoration: 'underline dotted' } }}>
                                {emp.first_name} {emp.last_name}
                              </Typography>
                            </Box>
                          </TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', borderRight: '1px solid #f0f0f0', py: 1 }}>
                            {isEditing ? (
                              <Select
                                value={isEditing.status}
                                onChange={(e) => handleRowInputChange(emp.id, 'status', e.target.value)}
                                size="small"
                                sx={{ fontSize: '0.8rem' }}
                              >
                                <MenuItem value="Present">Present</MenuItem>
                                <MenuItem value="Absent">Absent</MenuItem>
                                <MenuItem value="Leave">Leave</MenuItem>
                                <MenuItem value="Half Day">Half Day</MenuItem>
                              </Select>
                            ) : attendance ? (
                              <Box sx={{ display: 'inline-block', px: 1, py: 0.5, backgroundColor: attendance.status === 'Present' ? '#f0f7f0' : attendance.status === 'Absent' ? '#fef0f0' : '#fff3e0', borderRadius: '3px', color: attendance.status === 'Present' ? '#2e7d32' : attendance.status === 'Absent' ? '#c62828' : '#f57c00', fontSize: '0.75rem', fontWeight: 500 }}>
                                {attendance.status}
                              </Box>
                            ) : (
                              <Typography variant="caption" sx={{ color: '#999999' }}>-</Typography>
                            )}
                          </TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', borderRight: '1px solid #f0f0f0', py: 1 }}>
                            {isEditing ? (
                              <TextField
                                type="time"
                                value={isEditing.check_in}
                                onChange={(e) => handleRowInputChange(emp.id, 'check_in', e.target.value)}
                                size="small"
                                sx={{ fontSize: '0.8rem', width: '100px' }}
                                InputLabelProps={{ shrink: true }}
                              />
                            ) : (
                              attendance?.check_in || '-'
                            )}
                          </TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', borderRight: '1px solid #f0f0f0', py: 1 }}>
                            {isEditing ? (
                              <TextField
                                type="time"
                                value={isEditing.check_out}
                                onChange={(e) => handleRowInputChange(emp.id, 'check_out', e.target.value)}
                                size="small"
                                sx={{ fontSize: '0.8rem', width: '100px' }}
                                InputLabelProps={{ shrink: true }}
                              />
                            ) : (
                              attendance?.check_out || '-'
                            )}
                          </TableCell>
                          <TableCell sx={{ py: 1 }}>
                            {isEditing ? (
                              <Stack direction="row" spacing={0.5}>
                                <Button
                                  size="small"
                                  variant="contained"
                                  startIcon={<Save />}
                                  onClick={() => saveAttendanceRow(emp.id)}
                                  sx={{ fontSize: '0.65rem', textTransform: 'none', py: 0.3, px: 0.8, backgroundColor: '#2e7d32' }}
                                >
                                  Save
                                </Button>
                                <Button
                                  size="small"
                                  variant="outlined"
                                  startIcon={<Close />}
                                  onClick={() => cancelEditingRow(emp.id)}
                                  sx={{ fontSize: '0.65rem', textTransform: 'none', borderColor: '#e0e0e0', color: '#333333', py: 0.3, px: 0.8 }}
                                >
                                  Cancel
                                </Button>
                              </Stack>
                            ) : (
                              <Button
                                size="small"
                                variant="outlined"
                                startIcon={<Edit />}
                                onClick={() => startEditingRow(emp)}
                                sx={{ fontSize: '0.65rem', textTransform: 'none', borderColor: '#e0e0e0', color: '#333333', py: 0.3, px: 0.8 }}
                              >
                                Edit
                              </Button>
                            )}
                          </TableCell>
                        </TableRow>
                      );
                    })
                  )}
                </TableBody>
              </Table>
            </TableContainer>
          </CardContent>
        </Card>
      </Container>

      {/* Employee Attendance History Drawer */}
      <Drawer
        anchor="right"
        open={drawerOpen}
        onClose={closeEmployeeDrawer}
        sx={{
          '& .MuiBackdrop-root': {
            backgroundColor: 'rgba(0, 0, 0, 0.3)',
          },
          '& .MuiDrawer-paper': {
            width: 800,
            boxShadow: 'none',
            borderLeft: '1px solid #e0e0e0',
            zIndex: (theme) => theme.zIndex.drawer + 1,
          },
        }}
      >
        {selectedEmployee && (
          <Box sx={{ display: 'flex', flexDirection: 'column', height: '100vh' }}>
            <Box sx={{ p: 2, borderBottom: '1px solid #e0e0e0' }}>
              <Typography variant="h6" sx={{ fontWeight: 600, fontSize: '0.95rem' }}>
                {selectedEmployee.first_name} {selectedEmployee.last_name} - Attendance History
              </Typography>
            </Box>

            <Box sx={{ p: 2, overflowY: 'auto', flex: 1 }}>
            <Box sx={{ mb: 3, display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 2 }}>
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', border: '1px solid #f0f0f0', borderRadius: '4px', p: 1 }}>
                <Typography variant="body2" sx={{ fontSize: '0.8rem', color: '#333333' }}>From</Typography>
                <TextField
                  type="date"
                  value={rangeStart}
                  onChange={(e) => setRangeStart(e.target.value)}
                  InputLabelProps={{ shrink: true }}
                  size="small"
                  variant="standard"
                  sx={{
                    '& .MuiInput-underline:before': { borderBottom: 'none' },
                    '& .MuiInput-underline:hover:before': { borderBottom: 'none' },
                    '& .MuiInput-underline:after': { borderBottom: 'none' },
                  }}
                />
                <Typography variant="body2" sx={{ fontSize: '0.8rem', color: '#333333' }}>To</Typography>
                <TextField
                  type="date"
                  value={rangeEnd}
                  onChange={(e) => setRangeEnd(e.target.value)}
                  InputLabelProps={{ shrink: true }}
                  size="small"
                  variant="standard"
                  sx={{
                    '& .MuiInput-underline:before': { borderBottom: 'none' },
                    '& .MuiInput-underline:hover:before': { borderBottom: 'none' },
                    '& .MuiInput-underline:after': { borderBottom: 'none' },
                  }}
                />
              </Box>
              <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center', border: '1px solid #f0f0f0', borderRadius: '4px', p: 1 }}>
                <Button size="small" variant="text" startIcon={<Download />} onClick={() => downloadEmployeeHistory('csv')} sx={{ fontSize: '0.7rem', textTransform: 'none', color: '#333333', py: 0.3, px: 0.8 }}>
                  CSV
                </Button>
                <Button size="small" variant="text" startIcon={<Download />} onClick={() => downloadEmployeeHistory('pdf')} sx={{ fontSize: '0.7rem', textTransform: 'none', color: '#333333', py: 0.3, px: 0.8 }}>
                  PDF
                </Button>
              </Box>
            </Box>

              <TableContainer component={Paper} sx={{ border: 'none', boxShadow: 'none' }}>
                <Table size="small">
                  <TableHead>
                    <TableRow sx={{ backgroundColor: '#fafafa' }}>
                      <TableCell sx={{ fontWeight: 400, fontSize: '0.8rem', border: 'none' }}>Date</TableCell>
                      <TableCell sx={{ fontWeight: 400, fontSize: '0.8rem', border: 'none' }}>Status</TableCell>
                      <TableCell sx={{ fontWeight: 400, fontSize: '0.8rem', border: 'none' }}>Check In</TableCell>
                      <TableCell sx={{ fontWeight: 400, fontSize: '0.8rem', border: 'none' }}>Check Out</TableCell>
                    </TableRow>
                  </TableHead>
                  <TableBody>
                    {getFilteredAttendance().length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={4} sx={{ textAlign: 'center', py: 2, color: '#999999', fontSize: '0.8rem', border: 'none' }}>
                          No attendance records found
                        </TableCell>
                      </TableRow>
                    ) : (
                      getFilteredAttendance().map((record) => (
                        <TableRow key={record.id}>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none' }}>{record.date}</TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none' }}>
                            <Box sx={{ display: 'inline-block', px: 1, py: 0.5, backgroundColor: record.status === 'Present' ? '#f0f7f0' : record.status === 'Absent' ? '#fef0f0' : '#fff3e0', borderRadius: '3px', color: record.status === 'Present' ? '#2e7d32' : record.status === 'Absent' ? '#c62828' : '#f57c00', fontSize: '0.75rem', fontWeight: 500 }}>
                              {record.status}
                            </Box>
                          </TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none' }}>{record.check_in || '-'}</TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none' }}>{record.check_out || '-'}</TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </TableContainer>
            </Box>

            <Box sx={{ p: 2, borderTop: '1px solid #e0e0e0', display: 'flex', justifyContent: 'flex-end' }}>
              <Button onClick={closeEmployeeDrawer} variant="outlined" sx={{ fontSize: '0.8rem', textTransform: 'none' }}>
                Close
              </Button>
            </Box>
          </Box>
        )}
      </Drawer>
    </Layout>
  );
}
