import { Container, Typography, Card, CardContent, Button, Box, Grid, TextField, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper, Stack, MenuItem, Checkbox, FormControlLabel, Tooltip } from '@mui/material';
import { Edit, Delete, Add, Download } from '@mui/icons-material';
import Layout from '@/components/Layout';
import Breadcrumb from '@/components/Breadcrumb';
import { useEffect, useState } from 'react';
import api from '@/lib/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Employee {
  id: number;
  emp_id: string;
  first_name: string;
  last_name: string;
  salary: number;
  status: string;
}

interface PayrollData {
  emp_id: number;
  emp_name: string;
  salary: number;
  presentDays: number;
  halfDays: number;
  leaveDays: number;
  absentDays: number;
  workingDays: number;
  totalDays: number;
  dailyRate: number;
  grossSalary: number;
  deductions: number;
  netSalary: number;
}

const DAYS_OF_WEEK = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

const exportPayrollToCSV = (data: PayrollData[], filename: string) => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const headers = ['Employee ID', 'Employee Name', 'Salary', 'Present', 'Half Day', 'Leave', 'Absent', 'Working Days', 'Daily Rate', 'Gross Salary', 'Net Salary'];
  const csvContent = [
    headers.join(','),
    ...data.map(item => [
      item.emp_id,
      item.emp_name,
      item.salary,
      item.presentDays,
      item.halfDays,
      item.leaveDays,
      item.absentDays,
      item.workingDays,
      item.dailyRate,
      item.grossSalary,
      item.netSalary,
    ].join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.csv`;
  link.click();
  window.URL.revokeObjectURL(url);
};

const exportPayrollToPDF = (data: PayrollData[], filename: string, title: string, rangeStart: string, rangeEnd: string) => {
  if (data.length === 0) {
    alert('No data to export');
    return;
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // Add logo at top center with margin
  const logoUrl = '/logo-white.png';
  doc.addImage(logoUrl, 'PNG', pageWidth / 2 - 12, 10, 24, 24);
  
  // Add title
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(51, 51, 51);
  doc.text(title, pageWidth / 2, 45, { align: 'center' });
  
  // Add metadata
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text(`Period: ${rangeStart} to ${rangeEnd}`, pageWidth / 2, 52, { align: 'center' });
  doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, pageWidth / 2, 58, { align: 'center' });
  
  // Add table
  const headers = ['Employee ID', 'Employee Name', 'Salary', 'Present', 'Half Day', 'Leave', 'Absent', 'Working Days', 'Daily Rate', 'Gross Salary', 'Net Salary'];
  const rows = data.map(item => [
    item.emp_id,
    item.emp_name,
    `PKR ${item.salary.toLocaleString()}`,
    item.presentDays,
    item.halfDays,
    item.leaveDays,
    item.absentDays,
    item.workingDays,
    `PKR ${item.dailyRate.toLocaleString()}`,
    `PKR ${item.grossSalary.toLocaleString()}`,
    `PKR ${item.netSalary.toLocaleString()}`,
  ]);
  
  autoTable(doc, {
    head: [headers],
    body: rows,
    startY: 66,
    theme: 'grid',
    headStyles: {
      fillColor: [255, 255, 255],
      textColor: [51, 51, 51],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
      lineColor: [200, 200, 200],
      lineWidth: 0.2,
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [51, 51, 51],
      lineColor: [220, 220, 220],
      lineWidth: 0.2,
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250],
    },
    margin: { top: 66, right: 10, bottom: 20, left: 10 },
  });
  
  // Add footer
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.2);
  doc.line(10, pageHeight - 18, pageWidth - 10, pageHeight - 18);
  
  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by: Voltrix ERP', 10, pageHeight - 12);
  doc.text(`Document ID: ${filename}`, 10, pageHeight - 8);
  doc.text(`Status: Accepted`, pageWidth - 10, pageHeight - 12, { align: 'right' });
  doc.text(`Page 1`, pageWidth - 10, pageHeight - 8, { align: 'right' });
  
  doc.save(`${filename}.pdf`);
};

export default function Payroll() {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [activeEmployees, setActiveEmployees] = useState<Employee[]>([]);
  const [payrollData, setPayrollData] = useState<PayrollData[]>([]);
  const [attendanceData, setAttendanceData] = useState<any[]>([]);
  const [rangeStart, setRangeStart] = useState('');
  const [rangeEnd, setRangeEnd] = useState('');
  const [excludedDays, setExcludedDays] = useState<boolean[]>([true, false, false, false, false, false, true]); // Sunday and Saturday by default

  // Initialize date range to 25th of previous month to 5th of current month
  useEffect(() => {
    const today = new Date();
    const currentMonth = today.getMonth();
    const currentYear = today.getFullYear();
    
    let startDate, endDate;
    
    if (today.getDate() >= 25) {
      // If current date is >= 25, range is 25th of current month to 5th of next month
      startDate = new Date(currentYear, currentMonth, 25);
      endDate = new Date(currentYear, currentMonth + 1, 5);
    } else {
      // If current date is < 25, range is 25th of previous month to 5th of current month
      startDate = new Date(currentYear, currentMonth - 1, 25);
      endDate = new Date(currentYear, currentMonth, 5);
    }
    
    setRangeStart(startDate.toISOString().split('T')[0]);
    setRangeEnd(endDate.toISOString().split('T')[0]);
    
    fetchEmployees();
  }, []);

  useEffect(() => {
    if (rangeStart && rangeEnd) {
      calculatePayroll();
    }
  }, [rangeStart, rangeEnd, excludedDays, attendanceData]);

  const fetchEmployees = async () => {
    try {
      const response = await api.get('/api/employees');
      const active = response.data.filter((emp: Employee) => emp.status === 'Active');
      setEmployees(response.data);
      setActiveEmployees(active);
      
      // Fetch attendance data
      const attendanceResponse = await api.get('/api/attendance');
      setAttendanceData(attendanceResponse.data);
    } catch (error) {
      console.error('Error fetching data:', error);
    }
  };

  const calculatePayroll = () => {
    const data = activeEmployees.map(emp => {
      // Get attendance records for this employee in the date range
      const empAttendance = attendanceData.filter(
        a => a.emp_id === emp.id && a.date >= rangeStart && a.date <= rangeEnd
      );
      
      // Count days by status
      let presentDays = 0;
      let halfDays = 0;
      let leaveDays = 0;
      let absentDays = 0;
      
      empAttendance.forEach(record => {
        const dayOfWeek = new Date(record.date).getDay();
        
        // Skip excluded days (Sunday, Saturday, etc.)
        if (excludedDays[dayOfWeek]) {
          return;
        }
        
        switch (record.status) {
          case 'Present':
            presentDays++;
            break;
          case 'Half Day':
            halfDays++;
            break;
          case 'Leave':
            leaveDays++;
            break;
          case 'Absent':
            absentDays++;
            break;
        }
      });
      
      // Calculate working days (Present + Half Days + Leave)
      const workingDays = presentDays + (halfDays * 0.5) + leaveDays;
      const totalDays = 30;
      const dailyRate = emp.salary / 30;
      const grossSalary = dailyRate * workingDays;
      const deductions = 0;
      const netSalary = grossSalary - deductions;
      
      return {
        emp_id: emp.id,
        emp_name: `${emp.first_name} ${emp.last_name}`,
        salary: emp.salary,
        presentDays,
        halfDays,
        leaveDays,
        absentDays,
        workingDays: Math.round(workingDays * 100) / 100,
        totalDays,
        dailyRate: Math.round(dailyRate * 100) / 100,
        grossSalary: Math.round(grossSalary * 100) / 100,
        deductions,
        netSalary: Math.round(netSalary * 100) / 100,
      };
    });
    
    setPayrollData(data);
  };

  const toggleExcludedDay = (dayIndex: number) => {
    const newExcludedDays = [...excludedDays];
    newExcludedDays[dayIndex] = !newExcludedDays[dayIndex];
    setExcludedDays(newExcludedDays);
  };

  const getDatesByStatus = (empId: number, status: string): string[] => {
    return attendanceData
      .filter(a => a.emp_id === empId && a.date >= rangeStart && a.date <= rangeEnd && a.status === status)
      .map(a => a.date)
      .sort();
  };

  const totalGrossSalary = payrollData.reduce((sum, item) => sum + item.grossSalary, 0);
  const totalNetSalary = payrollData.reduce((sum, item) => sum + item.netSalary, 0);

  return (
    <Layout title="Payroll">
      <Container maxWidth="lg">
        <Breadcrumb
          items={[
            { label: 'Dashboard', href: '/' },
            { label: 'Human Resources' },
            { label: 'Payroll' },
          ]}
          prevHref="/attendance"
          nextHref="/"
        />

        <Box sx={{ mb: 3, display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: 1 }}>
          <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center', borderBottom: '1px solid #e0e0e0', pb: 0.5 }}>
            <Typography variant="body2" sx={{ fontSize: '0.8rem', color: '#333333' }}>From</Typography>
            <TextField
              type="date"
              value={rangeStart}
              onChange={(e) => setRangeStart(e.target.value)}
              InputLabelProps={{ shrink: true }}
              size="small"
              variant="standard"
              sx={{
                '& .MuiInput-underline:before': { borderBottom: 'none' },
                '& .MuiInput-underline:hover:before': { borderBottom: 'none' },
                '& .MuiInput-underline:after': { borderBottom: 'none' },
              }}
            />
            <Typography variant="body2" sx={{ fontSize: '0.8rem', color: '#333333' }}>To</Typography>
            <TextField
              type="date"
              value={rangeEnd}
              onChange={(e) => setRangeEnd(e.target.value)}
              InputLabelProps={{ shrink: true }}
              size="small"
              variant="standard"
              sx={{
                '& .MuiInput-underline:before': { borderBottom: 'none' },
                '& .MuiInput-underline:hover:before': { borderBottom: 'none' },
                '& .MuiInput-underline:after': { borderBottom: 'none' },
              }}
            />
          </Box>
          
          <Box sx={{ width: '1px', height: '24px', backgroundColor: '#e8e8e8', mx: 0.5 }} />
          
          <Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center' }}>
            <Button size="small" variant="text" onClick={() => exportPayrollToCSV(payrollData, `payroll_${rangeStart}_to_${rangeEnd}`)} sx={{ fontSize: '0.7rem', textTransform: 'none', color: '#333333', py: 0.3, px: 0.8 }}>
              <Download sx={{ fontSize: '0.9rem', mr: 0.5 }} /> CSV
            </Button>
            <Button size="small" variant="text" onClick={() => exportPayrollToPDF(payrollData, `payroll_${rangeStart}_to_${rangeEnd}`, `Payroll Report`, rangeStart, rangeEnd)} sx={{ fontSize: '0.7rem', textTransform: 'none', color: '#333333', py: 0.3, px: 0.8 }}>
              <Download sx={{ fontSize: '0.9rem', mr: 0.5 }} /> PDF
            </Button>
          </Box>
        </Box>

        <Card sx={{ border: 'none', boxShadow: 'none' }}>
          <CardContent sx={{ p: 0 }}>
            <TableContainer component={Paper} sx={{ border: 'none', boxShadow: 'none' }}>
              <Table>
                <TableHead>
                  <TableRow sx={{ backgroundColor: '#fafafa' }}>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Employee ID</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Name</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Salary</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Present</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Half Day</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Leave</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Absent</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Working Days</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Daily Rate</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Gross Salary</TableCell>
                    <TableCell sx={{ fontWeight: 400, color: '#333333', fontSize: '0.8rem', border: 'none', py: 1 }}>Net Salary</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {payrollData.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={11} sx={{ textAlign: 'center', py: 3, color: '#999999', fontSize: '0.8rem', border: 'none' }}>
                        No payroll data available
                      </TableCell>
                    </TableRow>
                  ) : (
                    <>
                      {payrollData.map((item, index) => (
                        <TableRow key={index} sx={{ '&:hover': { backgroundColor: '#fafafa' } }}>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>{item.emp_id}</TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>{item.emp_name}</TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>PKR {item.salary.toLocaleString()}</TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>
                            <Tooltip title={getDatesByStatus(item.emp_id, 'Present').join(', ') || 'No records'} arrow>
                              <Box sx={{ cursor: 'pointer', display: 'inline-block' }}>{item.presentDays}</Box>
                            </Tooltip>
                          </TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>
                            <Tooltip title={getDatesByStatus(item.emp_id, 'Half Day').join(', ') || 'No records'} arrow>
                              <Box sx={{ cursor: 'pointer', display: 'inline-block' }}>{item.halfDays}</Box>
                            </Tooltip>
                          </TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>
                            <Tooltip title={getDatesByStatus(item.emp_id, 'Leave').join(', ') || 'No records'} arrow>
                              <Box sx={{ cursor: 'pointer', display: 'inline-block' }}>{item.leaveDays}</Box>
                            </Tooltip>
                          </TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>
                            <Tooltip title={getDatesByStatus(item.emp_id, 'Absent').join(', ') || 'No records'} arrow>
                              <Box sx={{ cursor: 'pointer', display: 'inline-block' }}>{item.absentDays}</Box>
                            </Tooltip>
                          </TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>{item.workingDays}</TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>PKR {item.dailyRate.toLocaleString()}</TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1 }}>PKR {item.grossSalary.toLocaleString()}</TableCell>
                          <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1, fontWeight: 600 }}>PKR {item.netSalary.toLocaleString()}</TableCell>
                        </TableRow>
                      ))}
                      <TableRow sx={{ backgroundColor: '#f5f5f5', fontWeight: 600 }}>
                        <TableCell colSpan={8} sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1, fontWeight: 600 }}>
                          Total
                        </TableCell>
                        <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1, fontWeight: 600 }}>
                          -
                        </TableCell>
                        <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1, fontWeight: 600 }}>
                          PKR {totalGrossSalary.toLocaleString()}
                        </TableCell>
                        <TableCell sx={{ fontSize: '0.8rem', border: 'none', color: '#333333', py: 1, fontWeight: 600 }}>
                          PKR {totalNetSalary.toLocaleString()}
                        </TableCell>
                      </TableRow>
                    </>
                  )}
                </TableBody>
              </Table>
            </TableContainer>
          </CardContent>
        </Card>
      </Container>
    </Layout>
  );
}
